---
include:


    # nice_nano_v2 +  
# - board: nice_nano_v2
#   shield: corne_left  
#  cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_Oled\"
#   artifact-name: nice_corne_left_oled
#    snippet: studio-rpc-usb-uart
# - board: nice_nano_v2
#    shield: corne_right  
#    artifact-name: nice_corne_right_oled
#
    # peripheral_left + nice_nano_v2 +  
#  - board: nice_nano_v2
#    shield: corne_left_peripheral  
#    artifact-name: nice_corne_left_peripheral_oled

    # nice_nano_v2 dongle
#  - board: nice_nano_v2
#    shield: corne_dongle_pro_micro
#    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle\"
#    artifact-name: nice_corne_dongle_pro_micro
#    snippet: studio-rpc-usb-uart

#  - board: nice_nano_v2
#    shield: settings_reset
#    artifact-name: nice_settings_reset
  




    ###   START ###
    # nice_nano_v2 +  
  - board: nice_nano_v2
    shield: corne_left  
    cmake-args: 
      - -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_Oled\"
      - -DCONFIG_ZMK_MACRO=y  # Habilita macros
    artifact-name: nice_corne_left_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right  
    cmake-args: 
      - -DCONFIG_ZMK_MACRO=y  # Habilita macros
    artifact-name: nice_corne_right_oled

    # peripheral_left + nice_nano_v2 +  
  - board: nice_nano_v2
    shield: corne_left_peripheral  
    cmake-args: 
      - -DCONFIG_ZMK_MACRO=y  # Habilita macros
    artifact-name: nice_corne_left_peripheral_oled

    ### ProMicro_Dongle START ###
    # nice_nano_v2 dongle (macropad)
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro
    cmake-args: 
      - -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle\"
      - -DCONFIG_ZMK_MACRO=y  # Habilita macros
      - -DCONFIG_BT_MAX_CONN=3  # Conexões múltiplas
      - -DCONFIG_BT_MAX_PAIRED=3
      - -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=3
      - -DCONFIG_BT_CTLR_TX_PWR_PLUS_8=y  # Potência BLE
    artifact-name: nice_corne_dongle_pro_micro
    snippet: studio-rpc-usb-uart

    # Dongle com display (opcional)
  - board: nice_nano_v2
    shield: corne_dongle_pro_micro dongle_display
    cmake-args: 
      - -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle_O\"
      - -DCONFIG_ZMK_MACRO=y
      - -DCONFIG_BT_MAX_CONN=3
      - -DCONFIG_BT_MAX_PAIRED=3
      - -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=3
      - -DCONFIG_BT_CTLR_TX_PWR_PLUS_8=y
    artifact-name: nice_corne_dongle_oled
    snippet: studio-rpc-usb-uart
    ### Pro Micro END ###
  ### CORNE END ###

  ### SETTINGS_RESET START ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
